### ISSUE TITLE
Error: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by vbauer** [aweary/alder#10]
I've got the following error for some directories:

```bash
➜  java alder .
fs.js:968
  binding.stat(pathModule._makeLong(path), statValues);
          ^

Error: ENOENT: no such file or directory, stat '/Users/vbauer/Documents/workspace/java/bu/mbi/mbi-admin/build/ivy/tmp/lib/test/mbi-core-default.jar'
    at Object.fs.statSync (fs.js:968:11)
    at buildTree (/usr/local/lib/node_modules/@aweary/alder/alder.js:136:22)
    at buildTree (/usr/local/lib/node_modules/@aweary/alder/alder.js:184:7)
    at buildTree (/usr/local/lib/node_modules/@aweary/alder/alder.js:184:7)
    at buildTree (/usr/local/lib/node_modules/@aweary/alder/alder.js:184:7)
    at buildTree (/usr/local/lib/node_modules/@aweary/alder/alder.js:184:7)
    at buildTree (/usr/local/lib/node_modules/@aweary/alder/alder.js:184:7)
    at buildTree (/usr/local/lib/node_modules/@aweary/alder/alder.js:184:7)
    at buildTree (/usr/local/lib/node_modules/@aweary/alder/alder.js:184:7)
    at buildTree (/usr/local/lib/node_modules/@aweary/alder/alder.js:184:7)
```

**Comment by Spheerys** [comment]
I also have this error  :
```
fs.js:119
    throw err;
    ^

Error: ENOENT: no such file or directory, stat '/home/hedy/Documents/Documents de travail/2e lot/extraction-guide-v2.txt'
    at Object.statSync (fs.js:871:3)
    at buildTree (/usr/lib/node_modules/@aweary/alder/alder.js:136:22)
    at buildTree (/usr/lib/node_modules/@aweary/alder/alder.js:184:7)
    at buildTree (/usr/lib/node_modules/@aweary/alder/alder.js:184:7)
    at buildTree (/usr/lib/node_modules/@aweary/alder/alder.js:184:7)
    at buildTree (/usr/lib/node_modules/@aweary/alder/alder.js:184:7)
    at buildTree (/usr/lib/node_modules/@aweary/alder/alder.js:184:7)
    at buildTree (/usr/lib/node_modules/@aweary/alder/alder.js:184:7)
    at Object.<anonymous> (/usr/lib/node_modules/@aweary/alder/alder.js:193:1)
    at Module._compile (internal/modules/cjs/loader.js:816:30)

````

**Comment by Spheerys** [comment]
In fact alder stop working with : 
- specials characters on the filename
- inexistant symbolic link on a file

**Comment by rrthomas** [comment]
@Spheerys, I can reproduce the second problem (non-existent symbolic link makes alder stop with error) but not the first (non-ASCII character is displayed OK on my system).
